### ISSUE TITLE
ERROR ON PLAYER JOIN

### ISSUE THREAD

**Issue by LeoBdt** [thebigsmileXD/PocketRadio#9] opened 2019-06-02 13:57 UTC
2019-06-02 [15:56:14] [Server thread/CRITICAL]: ErrorException: "Object of class xenialdan\PocketRadio\libs\xenialdan\libnbs\Layer could not be converted to int" (EXCEPTION) in "plugins/PocketRadio_v3.0.1.phar/src/xenialdan/PocketRadio/Loader" at line 205
2019-06-02 [15:56:14] [Server thread/DEBUG]: #0 plugins/PocketRadio_v3.0.1.phar/src/xenialdan/PocketRadio/Loader(205): pocketmine\utils\Utils::errorExceptionHandler(integer 8, string Object of class xenialdan\PocketRadio\libs\xenialdan\libnbs\Layer could not be converted to int, string phar:///home/leo/skyblock/plugins/PocketRadio_v3.0.1.phar/src/xenialdan/PocketRadio/Loader.php, integer 205, array Array())
2019-06-02 [15:56:14] [Server thread/DEBUG]: #1 src/pocketmine/scheduler/TaskHandler(159): class@anonymous
2019-06-02 [15:56:14] [Server thread/DEBUG]: #2 src/pocketmine/scheduler/TaskScheduler(199): pocketmine\scheduler\TaskHandler->run(integer 832)
2019-06-02 [15:56:14] [Server thread/DEBUG]: #3 src/pocketmine/plugin/PluginManager(688): pocketmine\scheduler\TaskScheduler->mainThreadHeartbeat(integer 832)
2019-06-02 [15:56:14] [Server thread/DEBUG]: #4 src/pocketmine/Server(2558): pocketmine\plugin\PluginManager->tickSchedulers(integer 832)
2019-06-02 [15:56:14] [Server thread/DEBUG]: #5 src/pocketmine/Server(2334): pocketmine\Server->tick()
2019-06-02 [15:56:14] [Server thread/DEBUG]: #6 src/pocketmine/Server(2195): pocketmine\Server->tickProcessor()
2019-06-02 [15:56:14] [Server thread/DEBUG]: #7 src/pocketmine/Server(1774): pocketmine\Server->start()
2019-06-02 [15:56:14] [Server thread/DEBUG]: #8 src/pocketmine/PocketMine(266): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /home/leo/skyblock/, string /home/leo/skyblock/plugins/)
2019-06-02 [15:56:14] [Server thread/DEBUG]: #9 (1): require(string phar:///home/leo/skyblock/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

**Comment by inxomnyaa** [comment] 2019-06-02 18:42
Will recheck. Maybe sth did not commit/upload

**Comment by inxomnyaa** [comment] 2019-11-03 03:29
Duplicate of #8. Closing since definitely patched after rewrite.

**Closed as completed by inxomnyaa** 2019-11-03 03:29 UTC
