### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by gamegam** [thebigsmileXD/PocketRadio#50] opened 2024-06-19 14:12 UTC
[Wed_Jun_19-23.11.18-KST_2024.log](https://github.com/user-attachments/files/15902160/Wed_Jun_19-23.11.18-KST_2024.log)

[14:11:18.215] [Server thread/EMERGENCY]: Crash occurred while handling a packet from session: plug Plugins
[14:11:18.217] [Server thread/CRITICAL]: Error: "Call to a member function getSongTitleAndAuthorInfo() on null" (EXCEPTION) in "plugins/PocketRadio (1).phar/src/xenialdan/PocketRadio/task/PlaylistPlayTask" at line 19
--- Stack trace ---
  #0 plugins/PocketRadio (1).phar/src/xenialdan/PocketRadio/playlist/Playlist(109): xenialdan\PocketRadio\task\PlaylistPlayTask->__construct(object xenialdan\PocketRadio\playlist\Playlist#50283)
  #1 plugins/PocketRadio (1).phar/src/xenialdan/PocketRadio/EventListener(17): xenialdan\PocketRadio\playlist\Playlist->play(int 3)
  #2 pmsrc/src/event/RegisteredListener(61): xenialdan\PocketRadio\EventListener->onJoin(object pocketmine\event\player\PlayerJoinEvent#130068)
  #3 pmsrc/src/event/Event(63): pocketmine\event\RegisteredListener->callEvent(object pocketmine\event\player\PlayerJoinEvent#130068)
  #4 pmsrc/src/player/Player(895): pocketmine\event\Event->call()
  #5 pmsrc/src/network/mcpe/NetworkSession(955): pocketmine\player\Player->doFirstSpawn()
  #6 pmsrc/src/network/mcpe/handler/SpawnResponsePacketHandler(37): pocketmine\network\mcpe\NetworkSession->onClientSpawnResponse()
  #7 pmsrc/vendor/pocketmine/bedrock-protocol/src/SetLocalPlayerAsInitializedPacket(42): pocketmine\network\mcpe\handler\SpawnResponsePacketHandler->handleSetLocalPlayerAsInitialized(object pocketmine\network\mcpe\protocol\SetLocalPlayerAsInitializedPacket#130098)
  #8 pmsrc/src/network/mcpe/NetworkSession(468): pocketmine\network\mcpe\protocol\SetLocalPlayerAsInitializedPacket->handle(object pocketmine\network\mcpe\handler\SpawnResponsePacketHandler#186331)
  #9 pmsrc/src/network/mcpe/NetworkSession(406): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\SetLocalPlayerAsInitializedPacket#130098, string[2] q.)
  #10 pmsrc/src/network/mcpe/raklib/RakLibInterface(214): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[54] .c*dt....../..%.r.(.mv.R.ub...x..8021D...&,....H2!....)
  #11 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(40): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(int 0, string[63] ..}.9...'..\P.h5t..?<D..w.<...IV.......n:..a..]..?.X...4......))
  #12 pmsrc/src/network/mcpe/raklib/RakLibInterface(107): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#26822)
  #13 pmsrc/src/TimeTrackingSleeperHandler(58): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
  #14 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(120): pocketmine\TimeTrackingSleeperHandler->pocketmine\{closure}()
  #15 pmsrc/src/TimeTrackingSleeperHandler(77): pocketmine\snooze\SleeperHandler->processNotifications()
  #16 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(79): pocketmine\TimeTrackingSleeperHandler->processNotifications()
  #17 pmsrc/src/Server(1698): pocketmine\snooze\SleeperHandler->sleepUntil(float 1718806278.2036)
  #18 pmsrc/src/Server(1066): pocketmine\Server->tickProcessor()
  #19 pmsrc/src/PocketMine(355): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#6, object pocketmine\utils\MainLogger#2, string[30] C:\Users\plugi\Desktop\server\, string[38] C:\Users\plugi\Desktop\server\plugins\)
  #20 pmsrc/src/PocketMine(378): pocketmine\server()
  #21 C:/Users/plugi/Desktop/server/PocketMine-MP.phar(168): require(string[102] phar://C:/Users/plugi/AppData/Local/Temp/PocketMine-MP-phar-cache.0/PMMF7ED.tmp.)
--- End of exception information ---
[14:11:18.220] [Server thread/EMERGENCY]: 복구 불가능한 오류가 발생하여 서버에 크래시가 발생했습니다. 크래시 덤프를 만듭니다
[14:11:18.240] [Server thread/EMERGENCY]: "C:/Users/plugi/Desktop/server/crashdumps/Wed_Jun_19-23.11.18-KST_2024.log" 파일을 크래시 보관소에 업로드하고 버그 보고 페이지에 링크를 제출해 주세요. 가능한 한 많은 정보를 주시기 바랍니다.
[14:11:18.967] [Server thread/EMERGENCY]: 크래시 덤프가 자동으로 크래시 보관소에 제출되었습니다. https://crash.pmmp.io/view/11082802?access_token=7e6632990b7c42ec에서 보거나 ID #11082802을(를) 사용할 수 있습니다.
[14:11:18.973] [Server thread/EMERGENCY]: 서버를 강제로 종료하는 중입니다

**Comment by inxomnyaa** [comment] 2024-06-20 15:22
Duplicate of #48

Already resolved. Please learn how to correctly use GitHub to create issues, don't create a new issue for every comment, thanks.

**Closed as completed** 2024-06-20 15:23 UTC
Labels: duplicate, invalid
