### ISSUE TITLE
Why i set volume 50, and i dont hear song?

### ISSUE THREAD

**Issue by GuckTubeYT** [thebigsmileXD/PocketRadio#16] opened 2019-12-26 09:21 UTC
Please help me, Why i set volume 50, and i dont hear song?

**Comment by GuckTubeYT** [comment] 2019-12-26 09:46
when i set volume 100, i hear song

**Comment by GuckTubeYT** [comment] 2019-12-26 14:08
Lol, why not answered?

**Comment by inxomnyaa** [comment] 2019-12-26 17:37
Duplicate of #13 . Stop spamming the repo. Follow the Readme instructions and check the config.yml. Merry Xmas -.-

**Closed as completed by inxomnyaa** 2019-12-26 17:37 UTC
Labels: duplicate, invalid
